# Tarea06- Numpy
### Alumno: Arnaldo Ariel García

1 . Explicar para que se usa la librería NumPy, ejemplificar dos 2 casos.  
**Numpy** es una librería útil para realizar cálculos matemáticos, con numerosas herramientas capaz de manejar gran cantidad de datos y con mucha velocidad de procesamiento.

2 . Investigar como instalar NumPy.  
Para instalar Numpy en Windows. primero debemos tener el instalador de paquetes de python, luego en la linea de comandos podemos usar pip -m install numpy

3 . Instalar NumPy

4 . Utilizando NumPy  
- Crear una matriz de ceros
- Crear una matriz de unos
- Mostrar 2 ejemplo utilizando arange() y shape()
- Mostrar un ejemplo de operaciones con matrices (Sumar y Restar). Uno por operación
- Presentar 2 ejemplos de acceso a filas y columnas.


In [1]:
import numpy as np

print('Matriz de ceros-----')
ceros = np.zeros((3,4))
print(ceros)

print('Matriz de Unos------')
unos = np.ones((2,4,2))
print (unos)

print('Matriz vacia------')
vacia = np.empty((2,3))
print (vacia)

sec1 = np.arange(10,30,5)
sec2 = np.arange(1,20,2)
print('Secuencia 1: ',sec1)
print('Secuencia 2: ',sec2)
print('Dimensiones',unos.shape)

a = np.array([[2,-5,6],[3,4,-8],[9,7,0]])
b = np.array([[1,1,1],[2,2,2],[3,3,3]])

print('Suma ------')
print(a+b)
print(np.add(a,b))
print('Resta------')
print(a-b)
print(np.subtract(a,b))
print('Multiplicacion------')
print(np.multiply(a,b))
print(a*b)

print('Modificar elemento de matriz')
print(a)
a[1,1]=0
print(a)

print('Valor absoluto')
print(np.abs(a))

print(np.nditer(a))
for x in np.nditer(a):
    print(x, end=' » ')

Matriz de ceros-----
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matriz de Unos------
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
Matriz vacia------
[[6.23042070e-307 3.56043053e-307 1.60219306e-306]
 [2.44763557e-307 1.69119330e-306 1.78022342e-306]]
Secuencia 1:  [10 15 20 25]
Secuencia 2:  [ 1  3  5  7  9 11 13 15 17 19]
Dimensiones (2, 4, 2)
Suma ------
[[ 3 -4  7]
 [ 5  6 -6]
 [12 10  3]]
[[ 3 -4  7]
 [ 5  6 -6]
 [12 10  3]]
Resta------
[[  1  -6   5]
 [  1   2 -10]
 [  6   4  -3]]
[[  1  -6   5]
 [  1   2 -10]
 [  6   4  -3]]
Multiplicacion------
[[  2  -5   6]
 [  6   8 -16]
 [ 27  21   0]]
[[  2  -5   6]
 [  6   8 -16]
 [ 27  21   0]]
Modificar elemento de matriz
[[ 2 -5  6]
 [ 3  4 -8]
 [ 9  7  0]]
[[ 2 -5  6]
 [ 3  0 -8]
 [ 9  7  0]]
Valor absoluto
[[2 5 6]
 [3 0 8]
 [9 7 0]]
2 » -5 » 6 » 3 » 0 » -8 » 9 » 7 » 0 » 

5 . Crear un módulo propio e importar como módulo en otro programa para poder utilizar las funciones definidas en el (ver http://docs.python.org.ar/tutorial/3/modules.html)



In [ ]:
import numpy as np
print(np.abs(-20))

6 . Utilizando la librería numpy, realizar una función que reciba como parámetro dos matrices y retorne la  multiplicación entre ellas. Ej: multiplica_matrices(parametro1, parametro2)


7 . Escriba una función  utilizando NumPy para calcular el valor absoluto por elementos. 
     Ejemplo: valor_absoluto([-13.2, 162.5, .20]) y retorne [13 , 162.5, 0.2]


8 . Escriba un programa NumPy para crear una matriz de 3X4 e iterar sobre él. Investigar sobre nditer. (El ejemplo del ejercicio está en el PDF de la clase)