## Tarea07 - Vectores con Numpy
### Alumno: Arnaldo Ariel García


***
1- Crear un vector con valores dentro del rango 10 a 49

In [2]:
import numpy as np

vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


***
2- Invertir el vector

In [78]:
vector = np.array([2,3,5,6,8,9])
print(np.flip(vector))


[9 8 6 5 3 2]


***
3- Crear una matriz 3x3 con valores 1 a 9 y luego de 0 a 8

In [59]:
def matriz(ini,fila,colu):
    matriz = np.arange(ini,fila*colu+ini)
    mat2 = np.reshape(matriz,(fila,colu))
    print(mat2)
    
matriz(1,3,3)   #(inicio,fila,columna)
matriz(0,3,3)
matriz(-5,2,9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-5 -4 -3 -2 -1  0  1  2  3]
 [ 4  5  6  7  8  9 10 11 12]]


***
4- Encontrar los índices que no son ceros del arreglo [1,2,0,2,4,0,1,0,0,0,0,4,5,6,7,0]

In [73]:
arreglo = [1,2,0,2,4,0,1,0,0,0,0,4,5,6,7,0]
print(np.nonzero(arreglo)[0])

[ 0  1  3  4  6 11 12 13 14]


***
5- Crear un vector de 10 elementos con valores aleatorios.

In [40]:
import random as rnd
import numpy as np
vector = []
for i in range(10):
    valor = rnd.randint(0,100)
    vector = np.append(vector,valor)

print(vector)

[75. 54. 94. 86. 54. 22. 87. 21. 24. 77.]


***
6- Crear una matriz de 6x6 y que sus borde sean uno (1 )y en su interior se cero (0)

In [34]:
def cuadro1y0(fila,colu):
    for i in range(fila):
        print('1',end='')
        for j in range(colu-2):
            if (i==0)or(i==fila-1):
                print(' 1',end='')
            else:
                print(' 0',end='')
        print(' 1')

cuadro1y0(6,6)
#cuadro1y0(14,41)

1 1 1 1 1 1
1 0 0 0 0 1
1 0 0 0 0 1
1 0 0 0 0 1
1 0 0 0 0 1
1 1 1 1 1 1


***
7- Crear dos vectores al azar de la misma dimensión y comprobar si son iguales.

In [182]:
dim = 2
v1 = np.random.randint(0,9,dim).tolist()
v2 = np.random.randint(0,9,dim).tolist()
print(v1)
print(v2)
if v1==v2:
    print('Son iguales!!')
else:
    print('Distintos..')


[7, 3]
[7, 3]
Son iguales!!
